version: '3'
 
services:
  web:
    build: .
    volumes:
      - ./src/app:/usr/src/app
      - node_modules_volume:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    entrypoint: "/bin/sh -c 'npm install && npm install js-sha512 semantic-ui-react semantic-ui-css && yarn start'"
    stdin_open: true
 
volumes:
  node_modules_volume:
